############################
## Author
############################

author:
  name: Jeff Carstensen
  image: author.png
  greeting: "CyberSecurity Professional :tada:"
  icon: ":wave:"

############################
## Links
############################

links:
  - github: https://github.com/jc57965
  - email: mailto:jeff@jeffcarstensen.com
  - website: https://jeffcarstensen.com
  - linkedin: Https://www.linkedin.com/in/jeffcarstensen/
  - certifications: https://www.credly.com/users/jeff-carstensen/badges
  - youtube: https://www.youtube.com/@jc5796
  - x-twitter: https://twitter.com/jc57965
  - bluesky: https://bsky.app/profile/jc57965.bsky.social
  - instagram: https://www.instagram.com/jeff_carstensen/
  # - mastodon:
  # - reddit:
  # - telegram:
  # - whatsapp:
  # - signal:
  # - codepen:
  # - dev:
  # - discord:
  # - orcid:
  # - slack:
  # - stack-overflow:
  # - twitch:
  # - patreon:
  # - soundcloud:
  # - dribbble:
  # - stack-exchange:
  # - tiktok:
  # - keybase:
  # - flickr:
  # - tumblr:
  # - kickstarter:
  # - snapchat:
  # - bitbucket:
  # - bandcamp:
  # - etsy:
  # - spotify:
  # - pinterest:
  # - strava:
  # - untappd:
  # - skype:
  # - medium:
  # - foursquare:
  # - apple:
  # - amazon:
  # - google:
  # - paypal:
  # - windows:

############################
## Colunms of Links
############################

# between 2 & 6 columns are supported (both incl)
columns: 3

###########################
## Icon text
###########################

# add the icon name to each icon
icontext: true

############################
## Tooltips
############################

# add tooltips on all icons
tooltip: false

###############################
## OpenGraph & Twitter Cards
###############################

title: L1nkr
description: "site build with L1nkr & Hugo"
images:
  - thumbnail.png
